#Configuration for Dragon Shouts by Blaxcraft
#
#
# auto_update - Allow Dragon Shouts to update itself
#
# op_only - Require op for shouting
# op_bypass_cooldown - Ops can bypass the shout cooldown and use it indefinitely [Requires enable_cooldown to be true]
# permissions_enabled - require dragonshouts.shout.* perm
# enable_cooldown - enable cooldown for shouting
# require_learn - require non-ops to learn spells from permissions or word walls [Requires op_only to be false]
# enable_word_walls - enable ops to build word walls
# broadcast:
#	enabled - broadcast shout to nearby players
# 	range - range to broadcast shout to nearby players. set to 0 for infinite range
# 	format - format for broadcast : %p = player, %w = words, %n for shout name, Use '&' for color codes

auto_update: true

op_only: true
op_bypass_cooldown: false
permissions_enabled: false
enable_cooldown: true
require_learn: false
enable_word_walls: true
broadcast:
   enabled: true
   range: 15
   format: "%p&f: %w! &a[%n]"